### ISSUE TITLE
Found An Information Disclosure Vuln

### ISSUE THREAD

**Issue by mrcbax** [mxroute/mxroute_website#4]
Unfortunately the contact form on your site is gated behind payment. Contacting you here.

Might I suggest adding a `security.txt`?

https://securitytxt.org/

**Comment by mxroute** [comment]
Feel free to toss an email at jarland@mxroute.com. Interesting thought on the security.txt thing, gonna look at that a bit further.

**Comment by mxroute** [comment]
Haven't heard anything back, closing this out. Will be happy to hear from you at the mentioned email address.
